### ISSUE TITLE
skyldav multithreading does not seem to work as desired

### ISSUE THREAD

**Issue by wschlich** [xypron/skyldav#12]
all (currently 8) skyldav threads always sum up to 100% of 1 CPU core, never more (checked with htop). shouldn't skyldav be capable of using more than 1 CPU core?

**Comment by wschlich** [comment]
I've now observed the following:

When there's single threaded file operation workload, skyldav only uses 100% CPU maximum, even when using multiple threads.

Example
$ find /usr -type f -print0 | xargs -0 cat > /dev/null
...results in skyldav using 100% CPU, evenly distributed among all skyldav threads.

If I run the above command pipeline multiple times in screen, I see that skyldav uses an additional 100% CPU per instance of the command pipeline that is being run (4x find+cat == 400% CPU).

Is that expected?

**Comment by xypron** [comment]
Scanning a single file runs in a single thread. Only if a 2nd file is opened while the first is still being scanned, an other worker from the threadpool is used. I am not aware of clamav being able to parallelize scanning a single file.

**Comment by wschlich** [comment]
I see. Thanks :)
